main: studio.resonos.nano.NanoArenas
name: NanoArenas
version: 1.5
api-version: 1.20
authors:
  - Athulsib
depend:
  - FastAsyncWorldEdit
description: Fast asynchronous arena system. Developed by Resonos Studios.